### ISSUE TITLE
java.lang.ClassCastException: net.minecraft.inventory.ContainerWorkbench cannot be cast to org.spongepowered.api.block.tileentity.TileEntity

### ISSUE THREAD

**Issue by BrainStone** [CubeEngine/modules-extra#40]
ItemDuct apparently tries to call start the item transferring process when leaving the Crafting GUI of a workbench.

```
> [12:40:16] [Server thread/ERROR] [Sponge]: Could not pass InteractInventoryEvent$Open$Impl to Plugin{id=cubeengine-itemduct, name=CubeEngine - ItemDuct, version=1.1.2, description=Transfer items via glass pipes, url=http://cubeengine.org, authors=[CubeEngine Team], source=/home/container/./mods/plugins/itemduct.jar}
java.lang.ClassCastException: net.minecraft.inventory.ContainerWorkbench cannot be cast to org.spongepowered.api.block.tileentity.TileEntity
at org.cubeengine.module.itemduct.listener.ItemDuctTransferListener.promptActivation(ItemDuctTransferListener.java:138) ~[ItemDuctTransferListener.class:?]
at org.cubeengine.module.itemduct.listener.ItemDuctTransferListener.lambda$onOpenInventory$1(ItemDuctTransferListener.java:96) ~[ItemDuctTransferListener.class:?]
at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_161]
at org.cubeengine.module.itemduct.listener.ItemDuctTransferListener.onOpenInventory(ItemDuctTransferListener.java:96) ~[ItemDuctTransferListener.class:?]
at org.spongepowered.common.event.listener.OpenListener_ItemDuctTransferListener_onOpenInventory94.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:368) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:422) [SpongeEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractInventoryOpenEvent(SpongeCommonEventFactory.java:904) [SpongeCommonEventFactory.class:1.12.2-2611-7.1.0-BETA-2931]
at net.minecraft.server.management.PlayerInteractionManager.handleOpenEvent(PlayerInteractionManager.java:789) [or.class:?]
at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1258) [or.class:?]
at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zik000(NetHandlerPlayServer.java:2377) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) [pa.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [ma.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [ma.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2611-7.1.0-BETA-2931]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) [hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2931]
at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by Faithcaio** [comment]
duplicate #35
