### ISSUE TITLE
Exceptions on ItemTransfer and rightclicking pistions

### ISSUE THREAD

**Issue by BrainStone** [CubeEngine/modules-extra#43]
In the latest Snapshot of ItemDuct I get the following exceptions. Additionally crafting is broken.

**ItemTransfer**:

```
> [10:57:15] [Server thread/ERROR] [Sponge]: The Scheduler tried to run the task cubeengine-itemduct-S-223 owned by Plugin{id=cubeengine-itemduct, name=CubeEngine - ItemDuct, version=1.1.4-SNAPSHOT, description=Transfer items via glass pipes, url=http://cubeengine.org, authors=[CubeEngine Team], source=/home/container/./mods/plugins/itemduct-1.1.4-SNAPSHOT.jar}, but an error occured.
java.lang.NullPointerException: null
at org.cubeengine.module.itemduct.listener.ItemDuctTransferListener.activate(ItemDuctTransferListener.java:208) ~[ItemDuctTransferListener.class:?]
at org.spongepowered.api.scheduler.Task$Builder.lambda$execute$0(Task.java:139) ~[Task$Builder.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.common.scheduler.SyncScheduler.executeTaskRunnable(SyncScheduler.java:70) ~[SyncScheduler.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.common.scheduler.SchedulerBase.startTask(SchedulerBase.java:179) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.common.scheduler.SchedulerBase.processTask(SchedulerBase.java:165) ~[SchedulerBase.class:1.12.2-2611-7.1.0-BETA-2931]
at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707) [?:1.8.0_161]
at org.spongepowered.common.scheduler.SchedulerBase.runTick(SchedulerBase.java:108) [SchedulerBase.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.common.scheduler.SyncScheduler.tick(SyncScheduler.java:44) [SyncScheduler.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.common.scheduler.SpongeScheduler.tickSyncScheduler(SpongeScheduler.java:185) [SpongeScheduler.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.mod.SpongeMod.onTick(SpongeMod.java:278) [SpongeMod.class:1.12.2-2611-7.1.0-BETA-2931]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_SpongeMod_onTick_ServerTickEvent.invoke(.dynamic) [?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:651) [EventBus.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:589) [EventBus.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:278) [FMLCommonHandler.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:655) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Rightclicking**:

```
> [10:58:11] [Server thread/ERROR] [Sponge]: Could not pass InteractBlockEvent$Secondary$MainHand$Impl to Plugin{id=cubeengine-itemduct, name=CubeEngine - ItemDuct, version=1.1.4-SNAPSHOT, description=Transfer items via glass pipes, url=http://cubeengine.org, authors=[CubeEngine Team], source=/home/container/./mods/plugins/itemduct-1.1.4-SNAPSHOT.jar}
java.lang.NullPointerException: null
at org.cubeengine.module.itemduct.listener.ItemDuctTransferListener.lambda$onInteractPiston$3(ItemDuctTransferListener.java:121) ~[ItemDuctTransferListener.class:?]
at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_161]
at org.cubeengine.module.itemduct.listener.ItemDuctTransferListener.onInteractPiston(ItemDuctTransferListener.java:113) ~[ItemDuctTransferListener.class:?]
at org.spongepowered.common.event.listener.MainHandListener_ItemDuctTransferListener_onInteractPiston95.handle(Unknown Source) ~[?:?]
at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:335) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:312) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:364) [SpongeModEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:422) [SpongeEventManager.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:729) [SpongeCommonEventFactory.class:1.12.2-2611-7.1.0-BETA-2931]
at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractBlockEventSecondary(SpongeCommonEventFactory.java:708) [SpongeCommonEventFactory.class:1.12.2-2611-7.1.0-BETA-2931]
at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:1184) [or.class:?]
at net.minecraft.network.NetHandlerPlayServer.redirect$onProcessRightClickBlock$zik000(NetHandlerPlayServer.java:2377) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) [pa.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [ma.class:?]
at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [ma.class:?]
at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:149) [PacketUtil.class:1.12.2-2611-7.1.0-BETA-2931]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zla000(SourceFile:539) [hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:276) [SpongeImplHooks.class:1.12.2-2611-7.1.0-BETA-2931]
at net.minecraft.server.MinecraftServer.redirect$onRun$zjf000(MinecraftServer.java:4003) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

**Comment by Faithcaio** [comment]
Are you using latest SpongeForge? (for exact min. version see on Ore)
I fixed smth. in Sponge for custom data to work in recipes.
The exceptions are probably caused by the registration breaking earlier.

**Comment by BrainStone** [comment]
I use this version:

```
Minecraft: 1.12.2
SpongeAPI: 7.1.0-SNAPSHOT-6aa4e43
SpongeForge: 1.12.2-2611-7.1.0-BETA-2931
Minecraft Forge: 14.23.2.2611
```

**Comment by Faithcaio** [comment]
minimum for the dev build is `1.12.2-2611-7.1.0-BETA-2984`

**Comment by BrainStone** [comment]
Ok. I'll update and try again. Thanks!

**Comment by BrainStone** [comment]
Works 👍
